---
config:
  theme: default
  look: classic
  layout: elk
  class:
    hideEmptyMembersBox: true
---
classDiagram
direction TB
    class WorkflowEngine {
    }
    class WorkflowStep {
    }
    class WorkflowContext {
    }
    class Utils {
    }
    class SuperCli {
    }
    class EnvVarManager {
    }
    class CSPManager {
    }
    class CSPRegistry {
    }
    class CSP {
    }
    class GitCli {
    }
    class GitHubCli {
    }
    class TerraformCli {
    }
    class GcloudCli {
    }
    class VercelCli {
    }
    class AzureCli {
    }
    class NpxCli {
    }
    class CSPInputValues {
    }
    class TerraformVars {
    }

	<<singleton>> WorkflowEngine
	<<type>> WorkflowStep
	<<type>> WorkflowContext
	<<utility>> Utils
	<<abstract>> SuperCli
	<<singleton>> EnvVarManager
	<<singleton>> CSPManager
  <<singleton>> CSPRegistry
	<<interface>> CSP
	<<singleton>> GitCli
	<<singleton>> GitHubCli
	<<singleton>> TerraformCli
	<<singleton>> GcloudCli
	<<singleton>> VercelCli
  <<singleton>> AzureCli
	<<singleton>> NpxCli
	<<type>> CSPInputValues
	<<type>> TerraformVars

    WorkflowEngine --> WorkflowStep : contains
    WorkflowEngine --> WorkflowContext : manages
    WorkflowStep --> WorkflowContext : uses
    SuperCli <|-- GitCli : extends
    SuperCli <|-- GitHubCli : extends
    SuperCli <|-- TerraformCli : extends
    SuperCli <|-- NpxCli : extends
    SuperCli <|-- GcloudCli : extends
    SuperCli <|-- VercelCli : extends
    SuperCli <|-- AzureCli : extends
    CSP <|.. GcloudCli : implements
    CSP <|.. VercelCli : implements
    CSP <|.. AzureCli : implements
    CSPManager --> CSPRegistry : uses
    CSPRegistry --> CSP : manages
    CSPManager --> CSP : uses
    TerraformCli --> TerraformVars : creates
    CSPManager --> CSPInputValues : manages
    Utils --> EnvVarManager : uses
