---
config:
  theme: default
  look: classic
---
sequenceDiagram
    participant WE as WorkflowEngine
    participant WS as WorkflowStep

    loop for each step
        WE->>WS: check dependencies and conditions
        activate WS
        rect rgb(250,128,114)
        break dependencies or conditions<br> not met
            WS-->>WE: error
        end
        end
        WS-->>WE: dependencies and conditions met
        WE->>WS: execute(context)
        WS-->>WE: step completed
        deactivate WS
    end