---
config:
  theme: default
  look: classic
---
sequenceDiagram
    actor User
    participant CLI
    participant WE as WorkflowEngine
    participant WS as WorkflowStep
    
    User->>CLI: $ aboveit-cli deploy-fullstack
    activate CLI
    CLI->>CLI: createFullstackWorkflow()
    CLI->>WE: execute()
    activate WE

    loop for each step
        WE->>WS: execute()
        activate WS
        WS-->>WE: step completed
        deactivate WS
    end
    WE-->>CLI: workflow completed
    deactivate WE
    CLI-->>User: workflow execution completed -<br>deployment pipelines running
    deactivate CLI