---
config:
  theme: default
  look: classic
---
sequenceDiagram
    participant WE as WorkflowEngine
    participant CLI as CLI Tools<br>(GitHubCli, GitCli, TerraformCli)
    participant EnvMgr as EnvVarManager
    participant CSPMgr as CSPManager

    note right of WE: Step 1: initializeServices
    loop For each CLI tool
        WE->>CLI: getInstance()
        activate CLI
        CLI->>CLI: new CliInstance()
        CLI->>CLI: isCliInstalled()
        break CLI not installed
            CLI-->>WE: error
        end
        CLI-->>WE: CLI instance
        deactivate CLI
    end

    WE->>EnvMgr: getInstance()
    activate EnvMgr
    EnvMgr->>EnvMgr: new EnvVarManager() 
    EnvMgr-->>WE: EnvVarManager instance
    deactivate EnvMgr

     WE->>CSPMgr: getInstance()
    activate CSPMgr
    CSPMgr->>CSPMgr: new CSPManager()
    CSPMgr-->>WE: CSPManager instance
    deactivate CSPMgr