---
config:
  theme: default
  look: classic
---
sequenceDiagram
    actor User
    participant WE as WorkflowEngine
    participant GH as GitHubCli
    participant CSPM as CSPManager
    participant CSP as CSP

    note right of User: Step 3: collectUserInputs
    WE->>GH: setInputs()
    activate GH
    GH->>User: prompt for project name
    User-->>GH: enter project name
    alt user is part of at least one organization
        GH-->>User: prompt for wish to select organization
        alt user wants to select organization
            GH->>User: prompt for organization selection
            User-->>GH: select organization
        end
    end

    GH-->>WE: GitHub inputs collected
    deactivate GH
    
    WE->>CSPM: collectInputs()
    activate CSPM
    CSPM->>CSP: setInputs()
    activate CSP
    CSP->>User: prompt for CSP-specific inputs
    User-->>CSP: enter CSP inputs
    CSP-->>CSPM: CSP inputs collected
    CSPM->>CSP: normalizeInputs()
    CSP-->>CSPM: normalized inputs
    CSPM-->>WE: CSP inputs
    deactivate CSPM
    