---
config:
  theme: default
  look: classic
---
sequenceDiagram
    actor User
    participant WE as WorkflowEngine
    participant TF as TerraformCli
    
    box Remote Services
    participant TFExec as Terraform<br>Executable
    participant CSPAPI as CSP API<br>(GCP/Vercel)
    participant GHAPI as GitHub API
    end

    rect rgb(191, 223, 255)
    note right of User: Step 11: runTerraform
    WE->>TF: apply()
    activate TF
    TF->>TFExec: terraform apply
    activate TFExec
    TFExec->>CSPAPI: update resources
    activate CSPAPI
    CSPAPI-->>TFExec: resources updated
    deactivate CSPAPI
    TFExec->>GHAPI: create secrets and variables
    activate GHAPI
    GHAPI-->>TFExec: secrets and variables created
    TFExec->>GHAPI: create CI/CD pipeline
    GHAPI-->>TFExec: CI/CD pipeline created
    deactivate GHAPI
    TFExec-->>TF: infrastructure provisioned
    deactivate TFExec
    TF-->>WE: Full infrastructure provisioned
    deactivate TF
    WE-->>User: URL(s) for deployed services
    end