---
config:
  theme: default
  look: classic
---
sequenceDiagram
    participant WE as WorkflowEngine
    participant TF as TerraformCli
    
    box Remote Services
    participant TFExec as Terraform<br>Executable
    participant CSPAPI as CSP API
    participant GHAPI as GitHub API
    end

    note right of WE: Step 11: establishCD
    WE->>TF: apply()
    activate TF
    TF->>TFExec: terraform apply
    activate TFExec
    TFExec->>CSPAPI: update resources
    activate CSPAPI
    CSPAPI-->>TFExec: resources updated
    deactivate CSPAPI
    TFExec->>GHAPI: create secrets and variables
    activate GHAPI
    GHAPI-->>TFExec: secrets and variables created
    TFExec->>GHAPI: create CD pipeline
    GHAPI-->>TFExec: CD pipeline created
    deactivate GHAPI
    TFExec-->>TF: all infrastructure<br> and pipelines created
    deactivate TFExec
    TF-->>WE: full infrastructure provisioned
    deactivate TF