---
config:
  theme: default
  look: classic
---
sequenceDiagram
    participant WE as WorkflowEngine
    participant EVM as EnvVarManager
    actor User
    
    note right of WE: Step 4: setupEnvironmentVariables
    WE->>EVM: setEnvVars(*envVars definition*)
    activate EVM
    EVM-->>WE: EnvVar-definitions set
    WE->>EVM: collectEnvVars()
    activate EVM
    EVM->>User: prompt for multiple environments
    User-->>EVM: select environment option
    EVM->>User: prompt for common environment variables
    User-->>EVM: enter common variables
    
    alt Multiple Environments
        EVM->>User: prompt for staging environment variables
        User-->>EVM: enter staging variables
        EVM->>User: prompt for production environment variables
        User-->>EVM: enter production variables
    end
    
    EVM-->>WE: environment variables
    deactivate EVM

    